apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  labels:
    app: akhil-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akhil-webapp
  template:
    metadata:
      labels:
        app: akhil-webapp
    spec:
      containers:
      - name: akhil-webapp
        image: akhilesh86/akhil-devops-project
        ports:
        - containerPort: 80
